version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pgadmin123
      - POSTGRES_DB=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d evolution"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - evolution-net
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.2
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin123  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  evolution_instances:
  postgres_data:
  pgadmin_data:
  evolution_redis:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge